services:
  - type: web
    name: hsbau-rapport-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: ADMIN_KEY
        value: hsbau-admin-2024   # <-- Bitte ändern!
